### ISSUE TITLE
Can support cmd like tailf?

### ISSUE THREAD

**Issue by hanxi** [jprjr/sockexec#1]
I test run `tailf /tmp/xx.log`. But no response.

**Comment by jprjr** [comment]
Hi there - sorry for not responding to this sooner, I somehow completely missed these issues being open.

I just made a new release of sockexec (version 1.0.2) with some bugfixes, it's working properly with 'tail -f', can you confirm?

**Comment by hanxi** [comment]
![image](https://cloud.githubusercontent.com/assets/1185757/22647885/c5755fb4-ecae-11e6-8921-a2bc1c7b60a1.png)

It resolved. thanks.
