### ISSUE TITLE
Does not compile (Ubuntu 18.04) 

### ISSUE THREAD

**Issue by kaliwolf101** [jprjr/sockexec#14]
Hi, sockexec does not compile under Ubuntu 18.04, below is the error I receive when I run make

`kaliwolf@video:~/sockexec$ make
exec gcc -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -iquote src/include-local -Isrc/include -Wall -Wextra -Werror  -pipe -Wall -fPIC -std=c99 -O2  -c -o src/sockexec/sockexec.o src/sockexec/sockexec.c
src/sockexec/sockexec.c: In function ‘main’:
src/sockexec/sockexec.c:150:8: error: implicit declaration of function ‘tain_init’; did you mean ‘tain_uint’? [-Werror=implicit-function-declaration]
     if(tain_init() <= 0)               strerr_diefu1sys(111,"tain_init");
        ^~~~~~~~~
        tain_uint
cc1: all warnings being treated as errors
Makefile:130: recipe for target 'src/sockexec/sockexec.o' failed
make: *** [src/sockexec/sockexec.o] Error 1
kaliwolf@video:~/sockexec$
`
Thanks, 
Kali~

**Comment by jprjr** [comment]
What version of skalibs do you have installed?
