### ISSUE TITLE
can you build macosx version?

### ISSUE THREAD

**Issue by yingnierxiao** [jprjr/sockexec#3]
can you build macosx version?

**Comment by yingnierxiao** [comment]
make CFLAGS=-I../skalibs/src/include
mkdir -p bin
gcc -I../skalibs/src/include -o bin/sockexec src/accept_client.c src/child_read.c src/child_spawn3.c src/child_write.c src/cleanup.c src/client_read.c src/client_write.c src/close_connection.c src/dump_conne
ction.c src/dump_fds.c src/kill_processes.c src/process_signals.c src/route_event.c src/sockexec.c src/update_child.c src/update_client.c -lskarnet
In file included from src/accept_client.c:1:
src/common.h:15:10: fatal error: 'skalibs/uint.h' file not found
#include <skalibs/uint.h>
         ^
1 error generated.
make: *** [sockexec] Error 1

**Comment by jprjr** [comment]
Hey there! I've just tagged version 1.1.1-1, which includes a osx download.

This hasn't really been tested so YMMV

**Comment by jprjr** [comment]
Scratch that, it looks like on OSX it's pretty broken, I'm going to pull that release until I figure it out

**Comment by jprjr** [comment]
OK, there's a new version available (1.1.2) which includes a OSX download - give it a try!

**Comment by yingnierxiao** [comment]
local prog = require('resty.exec').new('/tmp/exec.sock')
    prog.bufsize = 10
    prog.stdout = function(v)
        ngx.log(ngx.ERR,v)
    end
    local res, err = prog("git","clone","giturl")
i try this code,but nothing print.

**Comment by jprjr** [comment]
Can you try this:

```
local prog = require('resty.exec').new('/tmp/exec.sock')
prog.bufsize = 10
prog.stdout = function(v)
   ngx.log(ngx.ERR,v)
end
prog.stderr = function(v)
   ngx.log(ngx.ERR,v)
end
local res, err = prog("git","clone","giturl")
if err then
  ngx.log(ngx.ERR,err)
end
```

**Comment by yingnierxiao** [comment]
this is [stderr(): Cloning into 'cok-public'...] stderr output,but stdout is nothing,i need [`**remote: Compressing objects:  92% (8309/9024)Receiving objects:  22% (2999/13235), 85.33 MiB | 5.38 MiB/s**` ]

**Comment by jprjr** [comment]
What's the current working directory of the sockexec process, and does it have permission to write there? Maybe try giving an absolute path to clone into, or git clone repourl /path/to/folder

On May 17, 2017 12:53:28 AM CDT, yingnierxiao <notifications@github.com> wrote:
>this is [stderr(): Cloning into 'cok-public'...] stderr output,but
>stdout is nothing,i need [`**remote: Compressing objects:  92%
>(8309/9024)Receiving objects:  22% (2999/13235), 85.33 MiB | 5.38
>MiB/s**` ]
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprjr/sockexec/issues/3#issuecomment-301992785

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
