### ISSUE TITLE
add debug args output,and DAEMON mode args

### ISSUE THREAD

**Issue by yingnierxiao** [jprjr/sockexec#5]

**Comment by jprjr** [comment]
Debug output is a good idea, but I'm fundamentally against adding a daemon mode. All the modern init systems prefer you run in the foreground (upstart, systemd, runit, s6, supervisor, launchd). If you need to fork to the background, you can use `start-stop-daemon` to write out a PID file and so on.

**Comment by jprjr** [comment]
Added a -d switch for a debug mode in version 1.2.0
