### ISSUE TITLE
Fail to compile with skalibs 2.5.0.0

### ISSUE THREAD

**Issue by paragasu** [jprjr/sockexec#6]
Sockexec not compatible with skalibs 2.5.0.0 and above because of api changes
From the release page:

`skalibs/ushort.h, skalibs/uint.h and skalibs/ulong.h removed. skalibs/types.h is now a generic header for fmtscan primitives for various types. 
`

**Comment by jprjr** [comment]
Done and done! Thanks for the report, I've updated the code to work with skalibs 2.5.0.0+, and updated the travis builds to use the newer skalibs.
