### ISSUE TITLE
mac simple test fail.

### ISSUE THREAD

**Issue by buhe** [jprjr/sockexec#9]
hey , thanks for good project, but 
```
./sockexec -d /tmp/exec.sock > sockexec.log 2>&1
```
and 
```
./sockexec.client /tmp/exec.sock bash
```

```
tail -f sockexec.log
```

output is 
```
Connection 0: accepted
Connection 0: reading client data
Connection 0: client sent 0 bytes, closing connection
Connection 0: attempting to close, forced
Connection 0: closing
```

what is miss? thx~

**Comment by jprjr** [comment]
That's expected - the sockexec client checks if standard input is a tty. If it is, it just closes standard input.

The client is meant to be a small demo program that runs short one-liners. I figured that can help debug the environment of the running sockexec process, it's not meant to be ssh-like and run interactively.

So for example, all of these should work:

```
./bin/sockexec.client /tmp/exec.sock bash -c 'echo $USER $PWD'
```

```
echo 'echo $USER $PWD' | ./bin/sockexec.client /tmp/exec.sock bash
```

```
echo '{"something":"anotherthing"}' | ./bin/sockexec.client /tmp/exec.sock json_pp
```

Please try those bash examples on MacOS and let me know if they work - I'm moving this week and my home Mac is all packed up, so it will be a bit until I can look into it.

**Comment by buhe** [comment]
Thanks man, I deal with it ,, but I forgot what i do .
I close this issue right now.
I reply this when i remember what i do, thanks.
